baseURL = "/"
languageCode = "en-us"
theme = "simple-intro"
title = "Theme Demo"

[params]
    mainbg = "https://cdn.discordapp.com/attachments/704599857083449366/722677588484423721/luca-bravo-XJXWbfSo2f0-unsplash_1.jpg"
    name = "John Doe"
    mainTitle = "Simple-intro"
    mainText = "Just simple intro theme for hugo"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"